/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

//import java.awt.List;
import ConnectDatabase.ConnectToXampp;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modun.banyanFlower;
import modun.listSaveInput;
import modun.singleFlower;

public class ViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewAddmin
     */
    private final List<singleFlower> listsinger = new ArrayList<>();
    private final List<banyanFlower> listbanyan = new ArrayList<>(); 
    private final List<listSaveInput>  listSaveOut = new ArrayList<>();
    private List<listSaveInput>  listSave = new ArrayList<>();
    private ViewInputList vInputList;
    private ViewOutputList vOutputList;
    private String typeFlower;
    private String typeFlowerKK;
    
    public ViewAdmin() {
        initComponents();
        uploadDataBase();
    }
    /**
     *
     * @return 
     */
    
    private void uploadDataBase(){
        listSave = ConnectToXampp.findAll();
//        System.out.println("Ok");
        listSave.forEach((listSaveInput e) -> {
            if((e.getType()).equals("Hoa đơn")){
                listsinger.add(new singleFlower(e.getpetalsFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            }else if((e.getType()).equals("Hoa đa")){
                listbanyan.add(new banyanFlower(e.getsubFlowerNum(), e.getName(), e.getCode(), e.getType(), e.getAmount(), e.getColor()));
            }
        });
        createTable(listsinger, listbanyan);
    }
    
    private void createTable(List<singleFlower> listFl, List<banyanFlower> listfl){
        
        Collections.sort(listfl, (banyanFlower o1, banyanFlower o2) -> {
            return o1.getCode().compareTo(o2.getCode());
        });
        Collections.sort(listFl, (singleFlower o1, singleFlower o2) -> {
            return o1.getCode().compareTo(o2.getCode());
        });
        DefaultTableModel table = new DefaultTableModel();
        listFlowerTable.setModel(table);
        table.addColumn("Mã hoa");
        table.addColumn("Tên hoa");
        table.addColumn("Loại hoa");
        table.addColumn("Màu sắc");
        table.addColumn("Số lượng");
        table.addColumn("Số hoa con");
        table.addColumn("Số cánh hoa");
        for(singleFlower flower : listFl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getAmount(), 0, flower.getPetalsFlowerNum()});
        }
        for(banyanFlower flower : listfl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getAmount(), flower.getSubFlowerNum(), 0});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlable = new javax.swing.JLabel();
        Codetxt = new javax.swing.JTextField();
        Nametxt = new javax.swing.JTextField();
        Colortxt = new javax.swing.JTextField();
        typeFlower1 = new javax.swing.JRadioButton();
        typeFlower2 = new javax.swing.JRadioButton();
        Amounttxt = new javax.swing.JTextField();
        subFlowerNumtxt = new javax.swing.JTextField();
        petalsFlowerNumtxt = new javax.swing.JTextField();
        OrderOuttxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFlowerTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cinBtn = new javax.swing.JButton();
        coutBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        codeKKtxt = new javax.swing.JTextField();
        typeFlower1KKtxt = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NameKKtxt = new javax.swing.JTextField();
        AmountKKtxt = new javax.swing.JTextField();
        typeFlower2KKtxt = new javax.swing.JRadioButton();
        resetBtn = new javax.swing.JButton();
        ResultBtn = new javax.swing.JButton();
        resetKKBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        navigationViewInputSave = new javax.swing.JMenuItem();
        navigationViewOutPutSave = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("GIAO DIỆN ADDMIN");

        jLabel3.setText("Mã Hoa");

        jLabel4.setText("Tên hoa");

        jLabel5.setText("Loại hoa");

        jLabel6.setText("Màu sắc");

        jLabel7.setText("Số lượng");

        jLabel8.setText("Số hoa con");

        jLabel9.setText("Số cánh hoa");

        jlable.setText("Số lượng xuất");

        buttonGroup1.add(typeFlower1);
        typeFlower1.setText("Hoa đa");
        typeFlower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(typeFlower2);
        typeFlower2.setText("Hoa đơn");
        typeFlower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlable, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeFlower1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(typeFlower2))
                    .addComponent(Codetxt)
                    .addComponent(Nametxt)
                    .addComponent(Colortxt)
                    .addComponent(Amounttxt)
                    .addComponent(subFlowerNumtxt)
                    .addComponent(petalsFlowerNumtxt)
                    .addComponent(OrderOuttxt))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Codetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeFlower1)
                    .addComponent(typeFlower2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Colortxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(petalsFlowerNumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OrderOuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(27, 27, 27))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nhập thông tin");

        listFlowerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu sắc", "Số lượng", "Số hoa con", "Số cánh hoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listFlowerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFlowerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFlowerTable);
        if (listFlowerTable.getColumnModel().getColumnCount() > 0) {
            listFlowerTable.getColumnModel().getColumn(0).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(1).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            listFlowerTable.getColumnModel().getColumn(2).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(3).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(4).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(5).setResizable(false);
            listFlowerTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Danh sách hoa trong kho");

        cinBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cinBtn.setText("Nhập");
        cinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinBtnActionPerformed(evt);
            }
        });

        coutBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        coutBtn.setText("Xuất ");
        coutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        removeBtn.setText("Xóa");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Kiểm kê");

        jLabel13.setText("Mã hoa");

        jLabel14.setText("Loại hoa");

        buttonGroup2.add(typeFlower1KKtxt);
        typeFlower1KKtxt.setText("Hoa đa");
        typeFlower1KKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower1KKtxtActionPerformed(evt);
            }
        });

        jLabel16.setText("Tên hoa");

        jLabel17.setText("Số lượng còn lại");

        buttonGroup2.add(typeFlower2KKtxt);
        typeFlower2KKtxt.setText("Hoa đơn");
        typeFlower2KKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFlower2KKtxtActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        ResultBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ResultBtn.setText("Kết quả ---->");
        ResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultBtnActionPerformed(evt);
            }
        });

        resetKKBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resetKKBtn.setText("Reset");
        resetKKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetKKBtnActionPerformed(evt);
            }
        });

        jMenu2.setText("Admin");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("Manager");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setText("Exporter");
        jMenu2.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("Importer");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Danh sách nhập/xuất");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        navigationViewInputSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navigationViewInputSave.setText("Phiếu nhập");
        navigationViewInputSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationViewInputSaveActionPerformed(evt);
            }
        });
        jMenu3.add(navigationViewInputSave);

        navigationViewOutPutSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navigationViewOutPutSave.setText("Phiếu xuất");
        navigationViewOutPutSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationViewOutPutSaveActionPerformed(evt);
            }
        });
        jMenu3.add(navigationViewOutPutSave);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setText("Nhập bằng file");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(487, 487, 487))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeFlower1KKtxt)
                                .addGap(30, 30, 30)
                                .addComponent(typeFlower2KKtxt)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetKKBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AmountKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn)
                        .addGap(45, 45, 45)
                        .addComponent(cinBtn)
                        .addGap(45, 45, 45)
                        .addComponent(coutBtn)
                        .addGap(45, 45, 45)
                        .addComponent(removeBtn)))
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(codeKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameKKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typeFlower1KKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AmountKKtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(typeFlower2KKtxt)
                                .addComponent(resetKKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cinBtn)
                            .addComponent(coutBtn)
                            .addComponent(removeBtn)
                            .addComponent(resetBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutBtnActionPerformed
        // TODO add your handling code here:
        Calendar Cal = Calendar.getInstance();
        int year = Cal.get(Calendar.YEAR);
        int month = Cal.get(Calendar.MONTH)+1;
        int day = Cal.get(Calendar.DAY_OF_MONTH);
        int hour = Cal.get(Calendar.HOUR_OF_DAY);
        int minute = Cal.get(Calendar.MINUTE);
        int second = Cal.get(Calendar.SECOND);
        
        String time = String.valueOf(second)+":"+String.valueOf(minute)+":"+String.valueOf(hour)+":"
                      +" "+String.valueOf(day)+"/"+String.valueOf(month)+"/"+String.valueOf(year);
        
        if(typeFlower.equals("Hoa đơn")){
            for(singleFlower flower : listsinger){
                if(Codetxt.getText().equals(flower.getCode())){
                    if(Double.parseDouble(OrderOuttxt.getText()) <= flower.getAmount()){
                        listSaveOut.add(new listSaveInput(flower.getName(), flower.getCode(), flower.getType(), flower.getColor(), Double.parseDouble(OrderOuttxt.getText()), 0, flower.getPetalsFlowerNum(), time));
                        flower.setAmount(flower.getAmount() - Double.parseDouble(OrderOuttxt.getText()));
                        createTable(listsinger, listbanyan);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Không đủ số lượng để xuất");
                    }
                }
            }
        }else{
            for(banyanFlower flower : listbanyan){
                if(Codetxt.getText().equals(flower.getCode())){
                    if(Double.parseDouble(OrderOuttxt.getText()) <= flower.getAmount()){
                        listSaveOut.add(new listSaveInput(flower.getName(), flower.getCode(), flower.getType(), flower.getColor(), Double.parseDouble(OrderOuttxt.getText()), flower.getSubFlowerNum(), 0, time));
                        flower.setAmount(flower.getAmount() - Double.parseDouble(OrderOuttxt.getText()));
                        createTable(listsinger, listbanyan);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Không đủ số lượng để xuất");
                    }
                }
            }
        }
        int index = 0;
        for(singleFlower flower : listsinger){
            if(flower.getAmount() == 0){
                listsinger.remove(index);
                return;
            }
            index++;
        }
        int indexx = 0;
        for(banyanFlower flower : listbanyan){
            if(flower.getAmount() == 0){
                listbanyan.remove(indexx);
                return;
            } else {
            }
            indexx++;
        }
        createTable(listsinger, listbanyan);
    }//GEN-LAST:event_coutBtnActionPerformed

    private void cinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinBtnActionPerformed
        // TODO add your handling code here:
        Calendar Cal = Calendar.getInstance();
        int year = Cal.get(Calendar.YEAR);
        int month = Cal.get(Calendar.MONTH)+1;
        int day = Cal.get(Calendar.DAY_OF_MONTH);
        int hour = Cal.get(Calendar.HOUR_OF_DAY);
        int minute = Cal.get(Calendar.MINUTE);
        int second = Cal.get(Calendar.SECOND);
        
        String time = String.valueOf(second)+":"+String.valueOf(minute)+":"+String.valueOf(hour)+":"
                      +" "+String.valueOf(day)+"/"+String.valueOf(month)+"/"+String.valueOf(year);
        
        String code = Codetxt.getText();
        String name = Nametxt.getText();
        String type = typeFlower;
        String color = Colortxt.getText();
        String amount = Amounttxt.getText();
        String subFlower = subFlowerNumtxt.getText();
        String petalsFlower = petalsFlowerNumtxt.getText();
        double mark = 0;
        
        if(code.equals("")||name.equals("")||type.equals("")||color.equals("")||subFlower.equals("")||petalsFlower.equals("")||amount.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Hãy điền đủ thông tin!");
            return;
        }
        if(Double.parseDouble(amount) <= 0){
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số dương!");
            return;
        }
        
            listSave.add(new listSaveInput(code, name, type, color, Double.parseDouble(amount), Double.parseDouble(subFlower), Double.parseDouble(petalsFlower), time));
        
        if(type.equals("Hoa đơn")){
            for(singleFlower flower : listsinger){
                if(code.equals(flower.getCode())){
                    flower.setAmount(Double.parseDouble(amount) + flower.getAmount());
                    createTable(listsinger, listbanyan);
                    mark = 1;
                }
            }
            if(mark == 0){
                listsinger.add(new singleFlower(Double.parseDouble(petalsFlower), name, code, type, Double.parseDouble(amount), color));
                createTable(listsinger, listbanyan);
            }
        }else{
            for(banyanFlower flower : listbanyan){
                if(code.equals(flower.getCode())){
                    flower.setAmount(Double.parseDouble(amount) + flower.getAmount());
                    createTable(listsinger, listbanyan);
                    mark = 1;
                }
            }
            if(mark == 0){
                listbanyan.add(new banyanFlower(Double.parseDouble(subFlower), name, code, type, Double.parseDouble(amount), color));
                createTable(listsinger, listbanyan);
            }
            
        }
    }//GEN-LAST:event_cinBtnActionPerformed

    private void typeFlower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower1ActionPerformed
        // TODO add your handling code here:
        typeFlower = "Hoa đa";
        petalsFlowerNumtxt.setText("0");
        subFlowerNumtxt.setText("");
    }//GEN-LAST:event_typeFlower1ActionPerformed

    private void typeFlower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower2ActionPerformed
        // TODO add your handling code here:
        typeFlower = "Hoa đơn";
        petalsFlowerNumtxt.setText("");
        subFlowerNumtxt.setText("0");
    }//GEN-LAST:event_typeFlower2ActionPerformed
    private void setInform(String code, String name, String type, String color, double amount, String subFlower, String petalsFlower){
        Codetxt.setText(code);
        Nametxt.setText(name);
        if(type.equals("Hoa đa")){
            typeFlower1.setSelected(true);
        }else{
            typeFlower2.setSelected(true);
        }
        Colortxt.setText(color);
        Amounttxt.setText(String.valueOf(amount));
        subFlowerNumtxt.setText(subFlower);
        petalsFlowerNumtxt.setText(petalsFlower);
    }
    private void listFlowerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFlowerTableMouseClicked
        // TODO add your handling code here:
        int selectRow = listFlowerTable.getSelectedRow();
        if(selectRow >= 0){
            String code = (String) listFlowerTable.getValueAt(selectRow, 0);
            String name = (String) listFlowerTable.getValueAt(selectRow, 1);
            String type = (String) listFlowerTable.getValueAt(selectRow, 2);
            typeFlower = type;
            String color = (String) listFlowerTable.getValueAt(selectRow, 3);
            double amount =  (double) listFlowerTable.getValueAt(selectRow, 4);
            String subFlower = (String) (listFlowerTable.getValueAt(selectRow, 5)+"");
            String petalsFlower = (String) (listFlowerTable.getValueAt(selectRow, 6)+"");
            setInform(code, name, type, color, amount, subFlower, petalsFlower);
        }
    }//GEN-LAST:event_listFlowerTableMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        Codetxt.setText("");
        Nametxt.setText("");
        buttonGroup1.clearSelection();
        Colortxt.setText( "");
        Amounttxt.setText(String.valueOf(""));
        subFlowerNumtxt.setText("");
        petalsFlowerNumtxt.setText("");
        OrderOuttxt.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void ResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultBtnActionPerformed
        // TODO add your handling code here:
        String code = codeKKtxt.getText();
        double mark = 0;
        if(typeFlowerKK.equals("Hoa đa")){
            for(banyanFlower flower : listbanyan){
                if(code.equals(flower.getCode())){
                    NameKKtxt.setText(flower.getName());
                    AmountKKtxt.setText(String.valueOf(flower.getAmount()));
                    mark = 1;
                }
            }
            if(mark == 0){
                NameKKtxt.setText("Không có dữ liệu");
                AmountKKtxt.setText("0.0");
            }
        }else{
            for(singleFlower flower : listsinger){
                if(code.equals(flower.getCode())){
                    NameKKtxt.setText(flower.getName());
                    AmountKKtxt.setText(String.valueOf(flower.getAmount()));
                    mark = 1;
                }
            }
            if(mark == 0){
                NameKKtxt.setText("Không có dữ liệu");
                AmountKKtxt.setText("0.0");
            }
        }
    }//GEN-LAST:event_ResultBtnActionPerformed

    private void typeFlower1KKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower1KKtxtActionPerformed
        // TODO add your handling code here:
        typeFlowerKK = "Hoa đa";
    }//GEN-LAST:event_typeFlower1KKtxtActionPerformed

    private void typeFlower2KKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFlower2KKtxtActionPerformed
        // TODO add your handling code here:
        typeFlowerKK = "Hoa đơn";
    }//GEN-LAST:event_typeFlower2KKtxtActionPerformed

    private void resetKKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetKKBtnActionPerformed
        // TODO add your handling code here:
        codeKKtxt.setText("");
        buttonGroup2.clearSelection();
        NameKKtxt.setText("");
        AmountKKtxt.setText("");
    }//GEN-LAST:event_resetKKBtnActionPerformed

    private void navigationViewInputSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationViewInputSaveActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        vInputList = new ViewInputList(listSave, this);
        vInputList.setVisible(true);
    }//GEN-LAST:event_navigationViewInputSaveActionPerformed

    private void navigationViewOutPutSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationViewOutPutSaveActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        vOutputList = new ViewOutputList(listSaveOut, this);
        vOutputList.setVisible(true);
    }//GEN-LAST:event_navigationViewOutPutSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountKKtxt;
    private javax.swing.JTextField Amounttxt;
    private javax.swing.JTextField Codetxt;
    private javax.swing.JTextField Colortxt;
    private javax.swing.JTextField NameKKtxt;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField OrderOuttxt;
    private javax.swing.JButton ResultBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cinBtn;
    private javax.swing.JTextField codeKKtxt;
    private javax.swing.JButton coutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlable;
    private javax.swing.JTable listFlowerTable;
    private javax.swing.JMenuItem navigationViewInputSave;
    private javax.swing.JMenuItem navigationViewOutPutSave;
    private javax.swing.JTextField petalsFlowerNumtxt;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton resetKKBtn;
    private javax.swing.JTextField subFlowerNumtxt;
    private javax.swing.JRadioButton typeFlower1;
    private javax.swing.JRadioButton typeFlower1KKtxt;
    private javax.swing.JRadioButton typeFlower2;
    private javax.swing.JRadioButton typeFlower2KKtxt;
    // End of variables declaration//GEN-END:variables

    private void listFlowerTableMouseClicked(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
