

package View;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import Model.DS_HoaDa;
import Model.DS_HoaDon;
import Model.HoaDa;
import Model.HoaDon;

/**
 *
 * @author HP
 */
public class DanhSachHoa extends javax.swing.JFrame {

	public DanhSachHoa() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		this.model = new DS_HoaDon();
		
		this.model_2 = new DS_HoaDa();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jTable.setBackground(new java.awt.Color(51, 0, 51));
		jTable.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
		jTable.setForeground(new java.awt.Color(255, 255, 255));
		jTable.setModel(
				new DefaultTableModel(new Object[][] {}, new String[] { "T\u00EAn hoa", "M\u00E3 hoa", " Lo\u1EA1i hoa",
						"  S\u1ED1 l\u01B0\u1EE3ng ", "M\u00E0u", "S\u1ED1 c\u00E1nh hoa", "S\u1ED1 hoa con" }));
		jScrollPane1.setViewportView(jTable);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Danh sách Hoa");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DanhSachHoa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DanhSachHoa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DanhSachHoa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DanhSachHoa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DanhSachHoa().setVisible(true);
			}
		});
	}

	public void hienDanhSach() {
		ArrayList<HoaDon> arr_HD;
		arr_HD = this.model.getDanhSachHoa();

		for (HoaDon hoaDon : arr_HD) {
			DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
			model_table.addRow(new Object[] { hoaDon.getTenHoa(), hoaDon.getMaHoa(), "Hoa đơn",
					hoaDon.getSoLuong() + "", hoaDon.getMauHoa(), hoaDon.getSoCanh() + "", "" });
		}

		for (HoaDa hoaDa : this.model_2.danhSachHoa) {
			DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
			model_table.addRow(new Object[] { hoaDa.getTenHoa(), hoaDa.getMaHoa(), "Hoa đơn", hoaDa.getSoLuong() + "",
					hoaDa.getMauHoa(), "", hoaDa.getSoHoaCon() + "" });
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable;
	
	
	private DS_HoaDon model;
	
	
	private DS_HoaDa model_2;
	// End of variables declaration//GEN-END:variables
}
