
package View;

import java.awt.Font;

import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import Controller.DS_HoaKho_Controller;
import Model.DS_HoaDa;
import Model.DS_HoaDon;
import Model.HoaDa;
import Model.HoaDon;

import javax.swing.GroupLayout;

/**
 *
 * @author HP
 */
public class SuaThongTin extends javax.swing.JFrame {

	public SuaThongTin() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		this.controller = new DS_HoaKho_Controller(null, null, null, null, null, null, null, null, null, null);
		Action action = new DS_HoaKho_Controller(null, null, null, null, null, null, null, null, null, this);
		this.model = new DS_HoaDon();
		this.model_2 = new DS_HoaDa();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField_ten = new javax.swing.JTextField();
		jTextField_id = new javax.swing.JTextField();
		sua_Button = new javax.swing.JToggleButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		luu_Button = new javax.swing.JToggleButton();
		tenSP_Field = new javax.swing.JTextField();
		maSP_Field = new javax.swing.JTextField();
		mauHoa_Field = new javax.swing.JTextField();
		soHoaCon_Field = new javax.swing.JTextField();
		soCanhHoa_Field = new javax.swing.JTextField();
		soLuong_Field = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Sửa Thông tin");

		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Nhập thong tin cũ");

		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Tên sản phẩm");

		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Mã sản Phẩm");

		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Loại hoa");

		jTextField_ten.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jTextField_id.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		sua_Button.setText("Chỉnh Sửa");
		sua_Button.addActionListener(action);

		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("Thông tin mới");

		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Tên Sản phẩm");

		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("Mã sản phẩm");

		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Màu");
		jLabel11.setToolTipText("m");

		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("Số hoa con");

		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("Số cánh hoa");

		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("Số lượng");

		luu_Button.setText("Lưu");
		luu_Button.addActionListener(action);

		tenSP_Field.setMinimumSize(new java.awt.Dimension(50, 22));

		this.hoaDon_RadioButton = new JRadioButton("Hoa đơn");
		hoaDon_RadioButton.setSelected(true);
		hoaDon_RadioButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		hoaDon_RadioButton.setBounds(774, 155, 103, 21);

		this.hoaDa_RadioButton = new JRadioButton("Hoa đa");
		hoaDa_RadioButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		hoaDa_RadioButton.setBounds(884, 155, 103, 21);

		btn_loaiHoa = new ButtonGroup();
		btn_loaiHoa.add(hoaDon_RadioButton);
		btn_loaiHoa.add(hoaDa_RadioButton);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(40).addGroup(jPanel1Layout
								.createParallelGroup(Alignment.TRAILING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jTextField_ten,
												GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel4)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jTextField_id))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(111).addComponent(jLabel5))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(94).addComponent(sua_Button))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(24)
								.addComponent(hoaDon_RadioButton, GroupLayout.PREFERRED_SIZE, 103,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(hoaDa_RadioButton, GroupLayout.PREFERRED_SIZE, 103,
										GroupLayout.PREFERRED_SIZE)))
				.addGap(140)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(tenSP_Field, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel11).addComponent(jLabel12).addComponent(jLabel13)
								.addComponent(jLabel14)).addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(maSP_Field).addComponent(mauHoa_Field)
										.addComponent(soHoaCon_Field).addComponent(soCanhHoa_Field)
										.addComponent(soLuong_Field, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
				.addContainerGap(110, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(103).addComponent(jLabel2)
						.addPreferredGap(ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
						.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE).addGap(167))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(262, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(254))
								.addGroup(
										jPanel1Layout.createSequentialGroup().addComponent(luu_Button).addGap(205)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(22).addComponent(jLabel1)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout
								.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2).addComponent(jLabel8))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3)
								.addComponent(jTextField_ten, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9).addComponent(tenSP_Field, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel4)
								.addComponent(jTextField_id, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel10).addComponent(maSP_Field, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel5)
										.addComponent(mauHoa_Field, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(6)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addComponent(hoaDon_RadioButton).addComponent(hoaDa_RadioButton))
										.addGap(14).addComponent(sua_Button))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(8)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jLabel12)
												.addComponent(soHoaCon_Field, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jLabel13)
												.addComponent(soCanhHoa_Field, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
						.addGap(18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel14)
								.addComponent(soLuong_Field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18).addComponent(luu_Button).addContainerGap(54, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.setBackground(new java.awt.Color(51, 0, 51));

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/red-home-icon.png"))); // NOI18N
		jLabel6.setText("Home");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/list1.png"))); // NOI18N
		jLabel7.setText("Danh sách");
		jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel7MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(29, 29, 29).addComponent(jLabel6)
						.addGap(37, 37, 37).addComponent(jLabel7)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel6).addComponent(jLabel7))
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked
		TrangChinh x = new TrangChinh();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_jLabel6MouseClicked

	private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel7MouseClicked
		DanhSachHoa x = new DanhSachHoa();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}// GEN-LAST:event_jLabel7MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SuaThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SuaThongTin().setVisible(true);
			}
		});
	}

	public void HienThi() {
		String maHoa = this.jTextField_id.getText();
		String tenHoa;
		String mauHoa;
		String textLoaihoa;
		int soLuong;
		int soCanhHoa;
		if (hoaDon_RadioButton.isSelected()) {
			HoaDon hd = new HoaDon();
			hd = this.model.infoHoaDon(maHoa);
			soCanhHoa = hd.getSoCanh();
			soCanhHoa_Field.setText(soCanhHoa + "");
			soHoaCon_Field.setText("");
			tenHoa = hd.getTenHoa();
			mauHoa = hd.getMauHoa();
			textLoaihoa = "Hoa Đơn";
			soLuong = hd.getSoLuong();
		} else {
			HoaDa hda = new HoaDa();
			hda = this.model_2.infoHoaDa(maHoa);
			int soHoaCon = hda.getSoHoaCon();
			soHoaCon_Field.setText(soHoaCon + "");
			soCanhHoa_Field.setText("");
			tenHoa = hda.getTenHoa();
			mauHoa = hda.getMauHoa();
			textLoaihoa = "Hoa Đa";
			soLuong = hda.getSoLuong();
		}

		tenSP_Field.setText(tenHoa + "");
		maSP_Field.setText(maHoa + "");
		mauHoa_Field.setText(mauHoa + "");
		soLuong_Field.setText(soLuong + "");
		if (tenSP_Field.getText().equals("")) {
			this.controller.thongBaoKhongTonTai();
		}
	}

	public void suaHoaKho() {
		String maHoaCu = this.jTextField_id.getText();
		String tenHoa = this.tenSP_Field.getText();
		String maHoa = this.maSP_Field.getText();
		String mauHoa = this.mauHoa_Field.getText();
		int soLuong = Integer.valueOf(this.soLuong_Field.getText());
		boolean loaiHoa = true;
		if (this.hoaDon_RadioButton.isSelected()) {
			this.model.xoaHoa(this.model.viTri(maHoaCu));
			loaiHoa = true;
			int soCanhHoa = Integer.valueOf(this.soCanhHoa_Field.getText());
			HoaDon hd = new HoaDon(tenHoa, maHoa, mauHoa, loaiHoa, soLuong, soCanhHoa);
			this.model.themHoa(hd);
		} else {
			this.model_2.xoaHoa(this.model_2.viTri(maHoaCu));
			loaiHoa = false;
			int soHoaCon = Integer.valueOf(this.soHoaCon_Field.getText());
			HoaDa hda = new HoaDa(tenHoa, maHoa, mauHoa, loaiHoa, soLuong, soHoaCon);
			this.model_2.themHoa(hda);

		}

	}

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextField_ten;
	private javax.swing.JTextField jTextField_id;
	private javax.swing.JTextField tenSP_Field;
	private javax.swing.JTextField maSP_Field;
	private javax.swing.JTextField mauHoa_Field;
	private javax.swing.JTextField soHoaCon_Field;
	private javax.swing.JTextField soCanhHoa_Field;
	private javax.swing.JTextField soLuong_Field;
	private javax.swing.JToggleButton sua_Button;
	private javax.swing.JToggleButton luu_Button;
	private ButtonGroup btn_loaiHoa;
	private JRadioButton hoaDon_RadioButton;
	private JRadioButton hoaDa_RadioButton;
	private DS_HoaKho_Controller controller;
	private DS_HoaDon model;
	private DS_HoaDa model_2;
}
