/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JFrame;
import View.DanhSachHoa;

/**
 *
 * @author HP
 */
public class TrangChinh extends javax.swing.JFrame {
	Color panedefault;
	Color panneClick;

	/**
	 * Creates new form trangchinh
	 */
	public TrangChinh() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		this.viewDS = new DanhSachHoa();
		jPanel1 = new javax.swing.JPanel();
		xoa = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		sua = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		bang = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		kiemke = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		xoa.setBackground(new java.awt.Color(0, 0, 0));
		xoa.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xoaMouseClicked(evt);
			}
		});

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Xóa sản phẩm");

		javax.swing.GroupLayout xoaLayout = new javax.swing.GroupLayout(xoa);
		xoa.setLayout(xoaLayout);
		xoaLayout.setHorizontalGroup(xoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(xoaLayout.createSequentialGroup().addContainerGap().addComponent(jLabel5)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						xoaLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3).addGap(22, 22, 22)));
		xoaLayout
				.setVerticalGroup(
						xoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(xoaLayout.createSequentialGroup().addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel3)));

		sua.setBackground(new java.awt.Color(0, 0, 0));
		sua.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				suaMouseClicked(evt);
			}
		});

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/fkx.png"))); // NOI18N

		jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Sửa sản phẩm");

		javax.swing.GroupLayout suaLayout = new javax.swing.GroupLayout(sua);
		sua.setLayout(suaLayout);
		suaLayout.setHorizontalGroup(suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(suaLayout.createSequentialGroup()
						.addGroup(suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(suaLayout.createSequentialGroup().addContainerGap().addComponent(jLabel6))
								.addGroup(suaLayout.createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel4)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		suaLayout.setVerticalGroup(suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(suaLayout.createSequentialGroup().addComponent(jLabel6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
						.addComponent(jLabel4)));

		bang.setBackground(new java.awt.Color(0, 0, 0));
		bang.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				bangMouseClicked(evt);
			}
		});

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/list.png"))); // NOI18N
		jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel8MouseClicked(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Danh sách");

		javax.swing.GroupLayout bangLayout = new javax.swing.GroupLayout(bang);
		bang.setLayout(bangLayout);
		bangLayout.setHorizontalGroup(bangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bangLayout.createSequentialGroup().addComponent(jLabel8).addGap(0, 6, Short.MAX_VALUE))
				.addGroup(bangLayout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		bangLayout
				.setVerticalGroup(
						bangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(bangLayout.createSequentialGroup().addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel1)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		jPanel4.setBackground(new java.awt.Color(0, 0, 0));

		kiemke.setBackground(new java.awt.Color(0, 0, 0));
		kiemke.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				kiemkeMouseClicked(evt);
			}
		});

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/check.png"))); // NOI18N

		jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Kiểm kê");

		javax.swing.GroupLayout kiemkeLayout = new javax.swing.GroupLayout(kiemke);
		kiemke.setLayout(kiemkeLayout);
		kiemkeLayout.setHorizontalGroup(kiemkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(kiemkeLayout.createSequentialGroup()
						.addGroup(kiemkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(kiemkeLayout.createSequentialGroup().addContainerGap().addComponent(jLabel7))
								.addGroup(
										kiemkeLayout.createSequentialGroup().addGap(38, 38, 38).addComponent(jLabel9)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		kiemkeLayout.setVerticalGroup(kiemkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(kiemkeLayout.createSequentialGroup().addComponent(jLabel7)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel9).addContainerGap()));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup().addGap(0, 56, Short.MAX_VALUE).addComponent(kiemke,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup().addGap(0, 8, Short.MAX_VALUE).addComponent(kiemke,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		jPanel5.setBackground(new java.awt.Color(51, 0, 51));

		jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Login-in-icon.png"))); // NOI18N
		jLabel11.setText("Đăng Nhâp");
		jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel11MouseClicked(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(204, 0, 204));
		jLabel13.setText("Quản lý chương trình");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel5Layout.createSequentialGroup().addContainerGap().addComponent(jLabel13)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel11).addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel5Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel13).addComponent(jLabel11))));

		jPanel3.setBackground(new java.awt.Color(0, 0, 0));

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pass.png"))); // NOI18N
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("Quản lý tài khoản");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(jLabel10))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel10)));

		jPanel6.setBackground(new java.awt.Color(102, 0, 102));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 28, Short.MAX_VALUE));

		jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/flw.png"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(105, 105, 105)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(64, 64, 64))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(37, 37, 37)
								.addComponent(bang, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(90, 90, 90)
								.addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(101, 101, 101)
								.addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap(61, Short.MAX_VALUE))
				.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel12)
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(204, 204, 204)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(bang, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(33, 33, 33)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel4, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jPanel3,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(83, 83, 83).addComponent(jPanel6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(222, 222, 222)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void bangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bangMouseClicked
		// TODO add your handling code here:
		DanhSachHoa x = new DanhSachHoa();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_bangMouseClicked

	private void xoaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_xoaMouseClicked
		Xoa x = new Xoa();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_xoaMouseClicked

	private void suaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_suaMouseClicked
		// TODO add your handling code here:
		SuaThongTin x = new SuaThongTin();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_suaMouseClicked

	private void kiemkeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kiemkeMouseClicked
		KiemKe x = new KiemKe();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_kiemkeMouseClicked

	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseClicked
		DanhSachHoa x = new DanhSachHoa();
		x.setVisible(true);
		this.viewDS.hienDanhSach();
		x.setVisible(true);	
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}// GEN-LAST:event_jLabel8MouseClicked

	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked
		QuanLyMatKhau x = new QuanLyMatKhau();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_jLabel2MouseClicked

	private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel11MouseClicked
		DangNhap x = new DangNhap();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_jLabel11MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TrangChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TrangChinh().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel bang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel kiemke;
	private javax.swing.JPanel sua;
	private javax.swing.JPanel xoa;
	private DanhSachHoa viewDS;
	// End of variables declaration//GEN-END:variables
}
