/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import Controller.DS_HoaKho_Controller;
import Model.DS_HoaDa;
import Model.DS_HoaDon;
import Model.HoaDa;
import Model.HoaDon;

/**
 *
 * @author HP
 */
public class Xuat extends javax.swing.JFrame {

	/**
	 * Creates new form xuat
	 */
	public Xuat() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		this.controller = new DS_HoaKho_Controller(null, null, null, null, null, null, null, null, null, null);
		Action action = new DS_HoaKho_Controller(null, null, null, null, null, null, this, null, null, null);
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tenSP_Field = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		maSP_Field = new javax.swing.JLabel();
		slXuat_Field = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		Button_xuat = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		textField_phieuXuat = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Xuất sản phẩm");

		tenSP_Field.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Loại Hoa");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Tên sản phẩm");

		maSP_Field.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		maSP_Field.setForeground(new java.awt.Color(255, 255, 255));
		maSP_Field.setText("Mã sản phẩm");

		slXuat_Field.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Số lượng xuất");

		Button_xuat.setBackground(new java.awt.Color(102, 0, 102));
		Button_xuat.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
		Button_xuat.setForeground(new java.awt.Color(255, 255, 255));
		Button_xuat.setText("Xuất");
		Button_xuat.addActionListener(action);

		jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Phiếu xuất");

		jTable.setBackground(new java.awt.Color(51, 0, 102));
		jTable.setForeground(new java.awt.Color(255, 255, 255));
		jTable.setModel(new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
				"T\u00EAn", "M\u00E3 hoa", "Lo\u1EA1i hoa", "S\u1ED1 l\u01B0\u1EE3ng", "M\u00E0u", "S\u1ED1 c\u00E1nh hoa", "S\u1ED1 hoa con"
			}
		));
		jScrollPane1.setViewportView(jTable);

		this.hoaDon_RadioButton = new JRadioButton("Hoa đơn");
		hoaDon_RadioButton.setSelected(true);
		hoaDon_RadioButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		hoaDon_RadioButton.setBounds(774, 155, 103, 21);

		this.hoaDa_RadioButton = new JRadioButton("Hoa đa");
		hoaDa_RadioButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		hoaDa_RadioButton.setBounds(884, 155, 103, 21);

		btn_loaiHoa = new ButtonGroup();
		btn_loaiHoa.add(hoaDon_RadioButton);
		btn_loaiHoa.add(hoaDa_RadioButton);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addGap(16)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(maSP_Field, GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE).addGap(129))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(97)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 278, GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel5)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(124).addComponent(Button_xuat,
								GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(134).addComponent(jLabel2))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(hoaDon_RadioButton, GroupLayout.PREFERRED_SIZE, 103,
										GroupLayout.PREFERRED_SIZE)
								.addGap(83)
								.addComponent(hoaDa_RadioButton, GroupLayout.PREFERRED_SIZE, 103,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED))
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 102,
												GroupLayout.PREFERRED_SIZE)
										.addGap(56).addComponent(slXuat_Field))
								.addComponent(textField_phieuXuat, GroupLayout.PREFERRED_SIZE, 353,
										GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 98,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(tenSP_Field, GroupLayout.PREFERRED_SIZE, 205,
												GroupLayout.PREFERRED_SIZE))))
				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 713, GroupLayout.PREFERRED_SIZE)
				.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(
										jPanel1Layout
												.createSequentialGroup()
												.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 447,
														GroupLayout.PREFERRED_SIZE)
												.addContainerGap(31, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(
												jLabel1, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
										.addGap(34)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(tenSP_Field, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(maSP_Field, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18).addComponent(jLabel2).addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(hoaDon_RadioButton).addComponent(hoaDa_RadioButton))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jLabel7)
												.addComponent(slXuat_Field, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addComponent(Button_xuat, GroupLayout.PREFERRED_SIZE, 36,
												GroupLayout.PREFERRED_SIZE)
										.addGap(13).addComponent(jLabel5).addGap(18).addComponent(textField_phieuXuat,
												GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
										.addGap(55)))));
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.setBackground(new java.awt.Color(153, 0, 153));

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/red-home-icon.png"))); // NOI18N
		jLabel8.setText("Home");
		jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel8MouseClicked(evt);
			}
		});

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/list1.png"))); // NOI18N
		jLabel6.setText("Danh sách");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel8)
						.addGap(44, 44, 44).addComponent(jLabel6)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(jLabel6))
						.addGap(0, 0, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(20, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel8MouseClicked
		// TODO add your handling code here:
		NguoiDung x = new NguoiDung();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(false);
	}// GEN-LAST:event_jLabel8MouseClicked

	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked
		DanhSachHoa x = new DanhSachHoa();
		x.setVisible(true);
		x.pack();
		x.setLocationRelativeTo(null);
		x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}// GEN-LAST:event_jLabel6MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Xuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Xuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Xuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Xuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Xuat().setVisible(true);
			}
		});
	}
	public void XuatHang() {
		String tenHoa = this.tenSP_Field.getText();
		String maHoa = this.maSP_Field.getText();
		if (hoaDon_RadioButton.isSelected()) {
			HoaDon hd = this.infoDon(maHoa);
			int soLuong = hd.getSoLuong();
			if (this.model.kiemTraTonTai_1(hd)) {
				if ((Integer.valueOf(soLuong) < Integer.valueOf(this.slXuat_Field.getText()))) {
					controller.thongBaoQuaSL();
				} else {
					soLuong -= Integer.valueOf(this.slXuat_Field.getText());

					if (soLuong == 0) {
						DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
						for (int i = 0; i < model_table.getRowCount(); i++) {
							String id = model_table.getValueAt(i, 1) + "";
							String textLoaihoa = model_table.getValueAt(i, 2) + "";
							if (id.equals(hd.getMaHoa()) && textLoaihoa.equals("Hoa đơn")) {
								this.model.xoaHoa(this.model.viTri(maHoa));
								model_table.removeRow(i);
							}
						}
					} else {
						this.updateHoaDon(hd);
					}
					df = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
					this.controller.thongBaoXuatThanhCong();
					this.textField_phieuXuat.setText(df.format(System.currentTimeMillis()) + " Xuất: "
							+ slXuat_Field.getText() + " " + tenHoa + " Mã hoa: " + maHoa + " Loại hoa: Đơn\n");
				}
			} else {
				controller.thongBaoKhongTonTai();
			}
		} else {

			HoaDa hda = this.infoDa(maHoa);
			if (hda.equals(null)) {
				controller.thongBaoKhongTonTai();
				return;
			}
			int soLuong = hda.getSoLuong();
			if (this.model_2.kiemTraTonTai_1(hda)) {
				if ((Integer.valueOf(soLuong) < Integer.valueOf(this.slXuat_Field.getText()))) {
					controller.thongBaoQuaSL();
				} else {
					soLuong -= Integer.valueOf(this.slXuat_Field.getText());
					if (soLuong == 0) {
						DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
						for (int i = 0; i < model_table.getRowCount(); i++) {
							String id = model_table.getValueAt(i, 1) + "";
							String textLoaihoa = model_table.getValueAt(i, 2) + "";
							soLuong = Integer.valueOf(model_table.getValueAt(i, 3) + "");
							if (id.equals(hda.getMaHoa()) && textLoaihoa.equals("Hoa đa")) {
								this.model_2.xoaHoa(this.model_2.viTri(maHoa));
							}
							model_table.removeRow(i);
						}
					}
					this.updateHoaDa(hda);

				}
				this.controller.thongBaoXuatThanhCong();
				this.textField_phieuXuat.setText(df.format(System.currentTimeMillis()) + " Xuất: "
						+ slXuat_Field.getText() + " " + tenHoa + " Mã hoa: " + maHoa + " Loại hoa: Đa\n");
			} else {
				controller.thongBaoKhongTonTai();
			}
		}
	}

	public void updateHoaDon(HoaDon hd) {
		DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
		this.model.updateHoaDon(hd);
		for (int i = 0; i < model_table.getRowCount(); i++) {
			String id = model_table.getValueAt(i, 1) + "";
			String loaiHoa = model_table.getValueAt(i, 2) + "";
			if (id.equals(hd.getMaHoa()) && loaiHoa.equals("Hoa đơn")) {
				model_table.setValueAt(hd.getTenHoa(), i, 0);
				model_table.setValueAt(hd.getMaHoa(), i, 1);
				model_table.setValueAt("Hoa đơn", i, 2);
				model_table.setValueAt(hd.getSoLuong(), i, 3);
				model_table.setValueAt(hd.getMauHoa(), i, 4);
				model_table.setValueAt(hd.getSoCanh(), i, 5);
				model_table.setValueAt("", i, 6);
			}
		}
	}

	public void updateHoaDa(HoaDa hda) {
		DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
		this.model_2.updateHoaDa(hda);
		for (int i = 0; i < model_table.getRowCount(); i++) {
			String id = model_table.getValueAt(i, 1) + "";
			String loaiHoa = model_table.getValueAt(i, 2) + "";
			if (id.equals(hda.getMaHoa()) && loaiHoa.equals("Hoa đa")) {
				model_table.setValueAt(hda.getTenHoa(), i, 0);
				model_table.setValueAt(hda.getMaHoa(), i, 1);
				model_table.setValueAt("Hoa đa", i, 2);
				model_table.setValueAt(hda.getSoLuong(), i, 3);
				model_table.setValueAt(hda.getMauHoa(), i, 4);
				model_table.setValueAt("", i, 5);
				model_table.setValueAt(hda.getSoHoaCon(), i, 6);
			}
		}
	}

	public HoaDon infoDon(String idDon) {
		DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
		int i_row = jTable.getSelectedRow();
		for (int i = 0; i < model_table.getRowCount(); i++) {
			String id = model_table.getValueAt(i, 1) + "";
			String textLoaihoa = model_table.getValueAt(i, 2) + "";
			if (id.equals(idDon) && textLoaihoa.equals("Hoa đa")) {
				String tenHoa = model_table.getValueAt(i_row, 0) + "";
				String maHoa = model_table.getValueAt(i_row, 1) + "";
				String mauHoa = model_table.getValueAt(i_row, 4) + "";
				int soLuong = Integer.valueOf(model_table.getValueAt(i_row, 3) + "");
				int soHoaCon = Integer.valueOf(model_table.getValueAt(i_row, 6) + "");
				HoaDon hd = new HoaDon(tenHoa, maHoa, mauHoa, true, soLuong, soHoaCon);
				return hd;
			}
		}
		return null;

	}

	public HoaDa infoDa(String idDa) {
		DefaultTableModel model_table = (DefaultTableModel) jTable.getModel();
		int i_row = jTable.getSelectedRow();
		for (int i = 0; i < model_table.getRowCount(); i++) {
			String id = model_table.getValueAt(i, 1) + "";
			String textLoaihoa = model_table.getValueAt(i, 2) + "";
			if (id.equals(idDa) && textLoaihoa.equals("Hoa đa")) {
				String tenHoa = model_table.getValueAt(i_row, 0) + "";
				String maHoa = model_table.getValueAt(i_row, 1) + "";
				String mauHoa = model_table.getValueAt(i_row, 4) + "";
				int soLuong = Integer.valueOf(model_table.getValueAt(i_row, 3) + "");
				int soHoaCon = Integer.valueOf(model_table.getValueAt(i_row, 6) + "");
				HoaDa hda = new HoaDa(tenHoa, maHoa, mauHoa, false, soLuong, soHoaCon);
				return hda;
			}
		}
		return null;

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Button_xuat;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel maSP_Field;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable;
	private javax.swing.JTextField tenSP_Field;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField textField_phieuXuat;
	private javax.swing.JTextField slXuat_Field;
	private DS_HoaKho_Controller controller;
	private DS_HoaDon model;
	private DS_HoaDa model_2;
	private ButtonGroup btn_loaiHoa;
	private JRadioButton hoaDon_RadioButton;
	private JRadioButton hoaDa_RadioButton;
	private DateFormat df;
}
